// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSZwEHekmoxldidzfZ03oT03jx4ZS5n7w',
    appId: '1:499004650651:web:4fef627a7d1dbdc885823e',
    messagingSenderId: '499004650651',
    projectId: 'kafajr-96360',
    authDomain: 'kafajr-96360.firebaseapp.com',
    databaseURL: 'https://kafajr-96360-default-rtdb.firebaseio.com',
    storageBucket: 'kafajr-96360.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByiEOlx0NzcOIajWADolA1uoJ32fNLeGI',
    appId: '1:499004650651:android:642bf317771a69bb85823e',
    messagingSenderId: '499004650651',
    projectId: 'kafajr-96360',
    databaseURL: 'https://kafajr-96360-default-rtdb.firebaseio.com',
    storageBucket: 'kafajr-96360.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSOKCOITaC3hu1ETDD5XkEymvzm9ZBeQA',
    appId: '1:499004650651:ios:21f61333a98800c385823e',
    messagingSenderId: '499004650651',
    projectId: 'kafajr-96360',
    databaseURL: 'https://kafajr-96360-default-rtdb.firebaseio.com',
    storageBucket: 'kafajr-96360.appspot.com',
    iosBundleId: 'com.example.kafaJr1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSOKCOITaC3hu1ETDD5XkEymvzm9ZBeQA',
    appId: '1:499004650651:ios:21f61333a98800c385823e',
    messagingSenderId: '499004650651',
    projectId: 'kafajr-96360',
    databaseURL: 'https://kafajr-96360-default-rtdb.firebaseio.com',
    storageBucket: 'kafajr-96360.appspot.com',
    iosBundleId: 'com.example.kafaJr1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSZwEHekmoxldidzfZ03oT03jx4ZS5n7w',
    appId: '1:499004650651:web:cb803699d5ae4f3585823e',
    messagingSenderId: '499004650651',
    projectId: 'kafajr-96360',
    authDomain: 'kafajr-96360.firebaseapp.com',
    databaseURL: 'https://kafajr-96360-default-rtdb.firebaseio.com',
    storageBucket: 'kafajr-96360.appspot.com',
  );

}